### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [zhaobozhen/Kage#12]
Could you please specify what license your code is under? Thanks!

**Comment by zhaobozhen** [comment]
thanks for reminding. I have added the licence.

**Comment by IzzySoft** [comment]
That was fast, thanks a lot!

Btw: you might wish to point out in the Readme that your app is also available at Play Store and (starting in about 6.5 hours) also [in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.absinthe.kage). If you resize the graphics, all three "badges" (CoolApk, PlayStore, [mine](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it)) should fit next to each other in a single row :smiley:

**Comment by zhaobozhen** [comment]
Your repo looks great! But sorry, this project is only for my graduation project and may no longer be maintained at any time in the future. So it is not going to guide users to download it.

**Comment by IzzySoft** [comment]
Oh – OK, I wasn't aware of that. A pity, really. Well, maybe you re-decide and keep it maintained :wink: All the best!
